# Generated by Django 4.0.4 on 2023-08-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generative_ai', '0002_about_alter_businessai_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrollCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icons')),
                ('industry', models.CharField(max_length=400)),
                ('idea', models.TextField()),
            ],
        ),
    ]
